

server:
  servlet:
    context-path: /mapstruct-showcase

### application properties

spring:
  application:
    name: mapstruct-showcase
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate.format_sql: true
  datasource:
    url: jdbc:h2:file:./data/mapstruct-showcase
    username: sa
    password: 
    driverClassName: org.h2.Driver
    
rest:
  server:
    enabled: true
    exception-handler:
      enabled: true

app:
  version: '@project.version@'

### actuator properties

management:
  endpoints:
    web:
      exposure:
        include: "*"
